### ISSUE TITLE
shape of the data 

### ISSUE THREAD

**Issue by YuJinSong412** [addb-swstarlab/DATATune#19]
Hello. 

I have a question about your code.

Why do you concatenate and then insert the configuration and metric values ​​as input to the autoencoder?

Thank you

**Comment by Kwon-sein** [comment]
hello 😸 
Thank you for the good question.

The reason for concating the configuration and metric value is that the metric contains information about the workload.

Even if the configuration is the same, there are different metrics depending on the workload, so the metrics include information about the workload, and our goal is to optimize for various workloads.

That's why we created a latent space by concatenating configuration and metrics.
