### ISSUE TITLE
latent space optimization

### ISSUE THREAD

**Issue by SkiddieAhn** [addb-swstarlab/DATATune#23]
Why did you use Bayesian Optimization (BO) for latent space optimization? Are there any issues with using Reinforcement Learning (RL)?

**Comment by Kwon-sein** [comment]
Hello,

Thank you for your interest in my code.

One significant drawback of using reinforcement learning (RL) for optimization is that it relies on a trial-and-error approach, which makes the process extremely time-consuming.

In fact, when comparing the tuning times between a baseline model optimized using RL and other approaches, we observed a substantial difference, with RL taking approximately 5-6 hours to complete.

Due to this limitation, we opted to use Bayesian Optimization (BO) instead of RL for optimizing within the latent space, as BO offers a more efficient alternative.

Thank you.
