### ISSUE TITLE
sample scaler question

### ISSUE THREAD

**Issue by HwanheeKim813** [addb-swstarlab/DATATune#4]
Hello,

In the code, the scale of new_X_ seems to be different from the scale of the data on which the regressor was trained. So I wonder why you use the new scaler Z_scaler instead of X_scaler. Is there another reason I'm not noticing?

Thank you.

**Comment by Kwon-sein** [comment]
Thank you for your interest in my code.

The reason why the scaler of new_X_ is different from the scaler of the regressor (I understand that TabNet) is that the input data of the regressor is original data X, but new_X data is the augmented data. It means two input data are different 
That's why they didn't use the same scaler.

If you have any additional questions, please leave an issue.

thank you.
