### ISSUE TITLE
Evaluate Alternative Scalers for Data Preprocessing in TADA.ipynb

### ISSUE THREAD

**Issue by Hyunjining** [addb-swstarlab/DATATune#5]
Hello,

In the `AutoEncoder` section of TADA.ipynb, data is scaled using `MinMaxScaler`. Considering different characteristics of datasets, exploring alternative scalers like `StandardScaler` or `RobustScaler` might improve model performance, especially if outliers are present or if data distributions vary. Could we look into testing these alternatives to compare their impacts on the AutoEncoder's effectiveness?

Thanks for considering this suggestion.

**Comment by Kwon-sein** [comment]
Thank you for the good question.

As  your mentioned, we can try using AutoEncoder's data not only with `MinMaxScaler` but also with other scalers.

In fact, when we scaled the data using `StandardScaler` and `MinMaxScale`r and used AutoEncoder, the best performance was obtained when `MinMaxScaler` was used for all column values ​​(parameters, tps, latency).

When we thought about the reason, first of all, the distribution of our data was not concentrated on one value. Because the distribution was even, it seemed to have better performance when scaled to a value between 0 and 1. 

Performance when using other scalers will be added later.

Thank you again for your interest in the code.
